### ISSUE TITLE
Overhaul config system (environment variables, multiple configs, and persistence through the admin plugin)

### ISSUE THREAD

**Issue by JohnMaguire** [JohnMaguire/Cardinal#93]
Disabling / enabling plugins in given channels, for example. This could be saved to a database, or probably preferably, a JSON file that can be modified. The main `config.json` could be used this way, but I'd sort of prefer that plugin config is kept separately. Probably should live in the `storage/` directory.

Because the `admin` plugin is used to load, unload, enable, and disable plugins, if it can store them persistently, it basically becomes the main configuration point of plugins in Cardinal. No more messing around with config.json for anything other than setting your network and optionally configuring the logger.

Theoretically, auto-joining of channels could be handled persistently by the `admin` plugin as well.

**Comment by JohnMaguire** [comment]
For a more global solution, something like this could be pretty cool:

```
plugins:
    admin:
        enabled: True
        whitelist: "#bots,whoami"
        blacklist: ""
        config:
            admins:
                - whoami@johnmaguire.me
```

```
{
  "plugins": {
    "admin": {
      "blacklist": "", 
      "enabled": true, 
      "whitelist": "#bots,whoami", 
      "config": {
        "admins": [
          "whoami@johnmaguire.me"
        ]
      }
    }
  }
}
```

This works nicely to do something like `.set plugins.admin.enabled false`, or `.append plugins.admin.config.admins jmaguire@my.vhost`, though an alternative to the addition of a new `.append`, we could just move to comma-separated lists for things like that.

**Comment by JohnMaguire** [comment]
Plugins could register config, with a default like so:

```python
@config('admins', "")
class AdminPlugin(object):
    pass
```

The second parameter being a default value.

**Comment by JohnMaguire** [comment]
Might as well do networks similarly:

```
darkscience:
    ssl: true
    address: "irc.darkscience.net"
    port: "6697"
    channels: "#bots"

freenode:
    ssl: true
    address: "irc.freenode.net"
    port: "6697"
    channels: "#bots"
```

**Comment by JohnMaguire** [comment]
Storage directory:
```
config/
    networks/
        freenode.yml
        darkscience.yml
        oftc.yml
    plugins/
        admin.yml
        urls.yml
database/
    freenode-notes.db
logs/
    freenode/
        cardinal.log
        cardinal.err.log
```

admin.yml
```yaml
enabled: True
whitelist:
    - #bots
    - whoami
networks:
    - darkscience:
        enabled: False
    - freenode:
        blacklist:
            - #bots
```

And then instead of `config.json`:
```
#!/bin/sh
STORAGE=$HOME/.cardinal
NETWORK=darkscience
NICK=Cardinal
NICKSERV_PASS=somepassword
PLUGINS=(admin urls)

./cardinal.py
```
